--- #YAML:1.0
name:                Test-HTTPStatus
version:             1.08
abstract:            check an HTTP status
license:             perl
author:              
    - brian d foy <bdfoy@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Carp:                          0
    HTTP::SimpleLinkChecker:       0
    Test::Builder:                 0
    Test::More:                    0
    URI:                           0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
