# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-HTTPStatus
version:      0.62
version_from: 
installdirs:  site
requires:
    Carp:                          0
    HTTP::SimpleLinkChecker:       0
    Test::Builder:                 0
    Test::More:                    0
    URI:                           0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
